### ISSUE TITLE
Change name of generated jar

### ISSUE THREAD

**Issue by ewencp** [confluentinc/camus#2]
@Ishiihara it looks like currently the jar generated is named camus-example-0.1.0-SNAPSHOT-shaded.jar. We should probably change the name to at least not include example, and maybe to include confluent to indicate it's our version with our decoder.

**Comment by Ishiihara** [comment]
Agreed, will work on that.

On Wed, Feb 4, 2015 at 6:37 PM, Ewen Cheslack-Postava <
notifications@github.com> wrote:

> @Ishiihara https://github.com/Ishiihara it looks like currently the jar
> generated is named camus-example-0.1.0-SNAPSHOT-shaded.jar. We should
> probably change the name to at least not include example, and maybe to
> include confluent to indicate it's our version with our decoder.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/confluentinc/camus/issues/2.

## 

Liquan Pei
Department of Physics
University of Massachusetts Amherst
