### ISSUE TITLE
CamusSweeper documentation

### ISSUE THREAD

**Issue by matthayes** [confluentinc/camus#22]
Is there any documentation on CamusSweeper and recommendations on how to run it?  The Camus docs at http://docs.confluent.io/1.0.1/camus/docs/index.html don't mention anything about the sweeper as far as I can see.  Can CamusSweeper be used?

**Comment by ewencp** [comment]
Note that Camus is now [deprecated](http://docs.confluent.io/3.0.0/camus/docs/intro.html) in favor of the [Kafka Connect HDFS connector](http://docs.confluent.io/3.0.0/connect/connect-hdfs/docs/index.html).

You can use `CamusSweeper` to aggregate from hourly to daily files. But this job needs to be triggered manually -- see the `camus-run` script fora sort of template for how to submit a Camus class as a job.
