### ISSUE TITLE
LinkedIn does not use Camus anymore

### ISSUE THREAD

**Issue by aragnon** [confluentinc/camus#32]
The website gives the impression that LinkedIn still uses Camus, which it probably doesn't. 

Camus is LinkedIn's previous generation Kafka to HDFS pipeline.

I would like to see two answers questioned: 
- Why do you not keep your documentation up to date?  
- Do you disagree on LinkedIn's vision on abandoning Camus, and if so, why?

**Comment by ewencp** [comment]
@aragnon 
- Yes, LinkedIn has moved to Gobblin for their Kafka -> HDFS pipeline.
- I'm not certain which documentation you are referring to. If you mean the README in this repository, we generally try to maintain minimal patches to the version of upstream Camus that we package for Confluent Platform. If you're referring to something in the Confluent Platform documentation that we've missed updating, please let us know more specifically.
- For Kafka -> HDFS, Confluent would recommend moving to [Kafka Connect](http://docs.confluent.io/2.0.0/connect/index.html) and the [HDFS connector](http://docs.confluent.io/2.0.0/connect/connect-hdfs/docs/index.html) developed by Confluent. However, we continue to support the version of Camus included in Confluent Platform. Using Kafka Connect has a number of benefits, including being very easy to get up and running, operational simplicity, and it makes it easy to run all sorts of connectors that copy data between Kafka and other systems.

**Comment by aragnon** [comment]
Thx for this clarification. I was referring to the github displayed readme. I will be giving the platform a spin (i.e., from source).

**Comment by ewencp** [comment]
@aragnon Great to hear you'll be trying out the platform. We'd love to hear any feedback you have on our [mailing list](https://groups.google.com/forum/#!forum/confluent-platform)!
